# Minimal Loki config – for production, use persistent storage and replication
loki:
  persistence:
    enabled: false
  config:
    table_manager:
      retention_deletes_enabled: true
      retention_period: 168h
