# Overrides for kube-prometheus-stack
grafana:
  enabled: false  # We already have Grafana from Loki stack
alertmanager:
  enabled: true
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    retention: 30d
    resources:
      requests:
        memory: 2Gi
        cpu: 500m
