[gateway]
public ansible_host=192.168.33.10 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/public/virtualbox/private_key

[private]
private ansible_host=192.168.33.11 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/private/virtualbox/private_key
